package test.jarTest;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.net.ssl.HttpsURLConnection;
import org.apache.commons.codec.digest.DigestUtils;

public class HotelBedsMd5 {
    public static void main(String[] args) {

        try {
            // Your API Key and secret
            String apiKey = "m3smp7z8j462xpd9u637jm9n";
            String Secret = "TjmuMBdDWX";
            // Signature is generated by SHA256 (Api-Key + Secret +
            // Timestamp (in seconds))
            String signature = DigestUtils
                .sha256Hex(apiKey + Secret + System.currentTimeMillis() / 1000);

            // Example of call to the API
            String endpoint = "https://api.hotelbeds.com/hotel-content-api/1.0/hotels?fields=all&language=CHI&from=1&to=30";
//            endpoint = "https://api.hotelbeds.com/hotel-content-api/1.0/types/facilities?fields=all&language=CHI&from=1&to=50";
//            endpoint = "https://api.hotelbeds.com/hotel-content-api/1.0/types/rooms?fields=all&language=CHI&from=1&to=100";
//            endpoint = "https://api.hotelbeds.com/hotel-content-api/1.0/types/imagetypes?fields=all&language=CHI&from=1&to=20";
//            endpoint = "https://api.hotelbeds.com/hotel-content-api/1.0/types/categories?fields=all&language=CHI&from=1&to=20";


//            endpoint = "https://api.hotelbeds.com/hotel-content-api/1.0/types/languages?fields=all&language=CHI&from=1&to=100";
//            endpoint = "https://api.hotelbeds.com/hotel-content-api/1.0/types/facilitygroups?fields=all&language=CHI&from=1&to=100";
//            endpoint = "https://api.hotelbeds.com/hotel-content-api/1.0/types/∂facilitytypologies?fields=all&language=CHI&from=1&to=100";
            URL url = new URL(endpoint);

            HttpsURLConnection connection = (HttpsURLConnection) url.openConnection();
            connection.setRequestProperty("X-Signature", signature);
            connection.setRequestProperty("Api-Key", apiKey);
            connection.setRequestProperty("Accept", "application/json");


            InputStream inputStream;

            int status = connection.getResponseCode();

            if (status != HttpURLConnection.HTTP_OK)
                inputStream = connection.getErrorStream();
            else
                inputStream = connection.getInputStream();

            InputStreamReader isr = new InputStreamReader(inputStream);
            BufferedReader in = new BufferedReader(isr);

            String inputLine;
            while ((inputLine = in.readLine()) != null) {
                System.out.print(inputLine);
            }
            in.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
